### ISSUE TITLE
Default install is missing payment table

### ISSUE THREAD

**Issue by klepek** [remp2020/crm-skeleton#1]
Hi,

I did default install, and when I try to create subscription type I end up with error (seems that subscription type is created as hidden)

![image](https://user-images.githubusercontent.com/656135/52328041-8dd4ce80-29ee-11e9-8675-e8abb13c8715.png)

**Comment by rootpd** [comment]
Thanks for the report, this seems like unwanted dependency to the module that wasn't released yet. We'll look into it and release a bugfix.

**Comment by rootpd** [comment]
This is now fixed, please run `composer update` on your skeleton project to get the latest version of modules.
