### ISSUE TITLE
Hermes update breaks CRM

### ISSUE THREAD

**Issue by j-norwood-young** [remp2020/crm-skeleton#2]
Fatal error: Class Crm\ApplicationModule\Hermes\HermesMessage contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Tomaj\Hermes\MessageInterface::getRetries) in /workspace/crm/vendor/remp/crm-application-module/src/hermes/HermesMessage.php on line 8

**Comment by rootpd** [comment]
I've just released version `0.4.0`  for all modules, the fix for the issue is included there. (https://github.com/remp2020/crm-application-module/commit/213940c07c33aa0a18404c66d959994ba5165bfa#diff-74bcaba505795462188b699c52f12a42)

**Comment by j-norwood-young** [comment]
Thanks, that fixed it, although just a note: I had to manually change my `composer.json` to pick up the update:

```
"require": {
                "remp/crm-application-module": "^0.4.0"
}
```

`composer update`

**Comment by rootpd** [comment]
Yeah, this is actually the feature of composer. For all pre-`1.0.0` versions, Composer expects that `0.3`->`0.4` might include breaking changes and won't bump the version if you use caret (`^`) to specify the versions. Tilde `~` would bump it.

https://getcomposer.org/doc/articles/versions.md#caret-version-range-
