### ISSUE TITLE
Settings not translated

### ISSUE THREAD

**Issue by j-norwood-young** [remp2020/crm-skeleton#3]
admin/config-admin/ - Not translated at all
<img width="1262" alt="Screenshot 2019-07-23 at 10 20 52" src="https://user-images.githubusercontent.com/387601/61695353-a2eeb100-ad33-11e9-9b1e-912437113f29.png">

**Comment by rootpd** [comment]
Internal ref: `remp/crm#773`

**Comment by rootpd** [comment]
Closing this as resolved. Settings since the version `0.6` now reference the translation file key instead of being slovak. It was release last year in October, we forgot to close this issue at the time.
