### ISSUE TITLE
LocaleAwareInterface incompatibility by TranslatorInterface newer version

### ISSUE THREAD

**Issue by PayteR** [remp2020/crm-skeleton#8]
The application will not work by default, because of interfaces incompatibility 
```
Declaration of Symfony\Component\Translation\TranslatorInterface::setLocale($locale) must be compatible with Symfony\Contracts\Translation\LocaleAwareInterface::setLocale(string $locale)
```
It's present on fresh project. This erros is present even on other project, for example SSO https://github.com/remp2020/remp/tree/master/Sso

To fix this is important to downgrade this packages in `composer.json` files on local project for now 
```
        "symfony/console": "^4.4",
        "symfony/translation-contracts": "^1"
```
But of course this should be better fixed on remp's side.

**Comment by rootpd** [comment]
This looks like a local environment issue. See:

* https://laracasts.com/discuss/channels/general-discussion/all-new-laravel-instances-are-broken-with-laravel-installer?page=0
* https://github.com/symfony/symfony/issues/34506
* https://github.com/symfony/symfony/issues/34482

Based on the provided versions of libraries you linked it also looks like you're running PHP 7.1 which is [no longer supported](https://www.php.net/supported-versions.php). We recommend updating PHP to (at least) v7.2.
